# Integrating the R package into the physical system

## Summary

An R package is not enough to run an analysis -- something needs to physically call the functions inside the R package. That is, the R package needs to be integrated into the physical system.

Everything related to integrating the R package into the physical system lives in the [dashboards](https://github.com/folkehelseinstituttet/dashboards/) repository.

Inside the [dashboards](https://github.com/folkehelseinstituttet/dashboards/) repository we have:

```
- dev/
  |-- src/
    |-- sykdomspuls/
       |-- 0_run.sh
       |-- RunProcess.R
       |-- RunTest.R
    |-- normomo/
       |-- 0_run.sh
       |-- RunProcess.R
       |-- RunTest.R
    |-- sykdomspuls_log/
       |-- 0_run.sh
       |-- RunProcess.R
       |-- RunTest.R
    |-- sykdomspuls_pdf/
       |-- 0_run.sh
       |-- RunProcess.R
       |-- RunTest.R
```

## RunProcess.R

### Aim

An automated analysis needs to:

1. Know the location of the data/results folders.
2. Check for new data in these folders. If no new data - then quit.
3. Load in the data.
4. Load in the analysis functions.
5. Run the analyses.
6. Save the results.

`RunProcess.R` is responsible for these tasks.

We can think of it as an extremely short and extremely high-level script that implements the analysis scripts.

Depending on the automated analysis `RunProcess.R` can be run every two minutes (constantly checking for new data), or once a week (when we know that data will only be available on a certain day/time).

### Bounded context

1. Only one instance of `RunProcess.R` can be run at a time.
2. Data only exists on physical folders on the system.
3. The following folder structure exists on the system (here the name of the automated analysis is `ANALYSIS`):

```
/data_raw/
  |-- ANALYSIS/
/data_clean/
  |-- ANALYSIS/
/data_app/
  |-- ANALYSIS/
/results/
  |-- ANALYSIS/
/src/
  |-- ANALYSIS/
     |-- 0_run.sh
     |-- RunProcess.R
     |-- RunTest.R
```

Point #1 is important because if `RunProcess.R` is run every 2 minutes (constantly checking for new data) but the analyses take 3 hours to run, then we need to ensure that only one instance of `RunProcess.R` can be run at a time.

Point #2 is important because sometimes:

1. Data files need to be downloaded from external SFTP servers ([normomo](https://folkehelseinstituttet.github.io/dashboards_normomo/), [sykdomspulslog](https://folkehelseinstituttet.github.io/dashboards_sykdomspuls_log/)).
2. Results files need to be uploaded to external SFTP servers ([sykdomspuls](https://folkehelseinstituttet.github.io/dashboards_sykdomspuls/)).

If we include code to download/upload the files from SFTP servers inside `RunProcess.R` then it makes it very difficult to test `RunProcess.R` (because we will then need to simulate SFTP servers inside our testing infrastructure). If we know that `RunProcess.R` only accesses files that are available on physical folders in the system, then our testing infrastructure is a lot easier to create and maintain.

## 0_run.sh

### Aim

The aim of `0_run.sh` is to ensure that:

1. Points 1 and 2 of the bounded context of `RunProcess.R` happen
2. Run `RunProcess.R`

With regards to the bounded context, we ensure that only one instance of `RunProcess.R` is run at a time through the use of `flock`.

(If neccessary) with regards to the bounded context, we use `sshpass`, `sftp`, and `ncftpput` to download/upload files from SFTP servers.

We then run `RunProcess.R` with a standard call:

```
/usr/local/bin/Rscript /src/ANALYSIS/RunProcess.R
```

## RunTest.R

### Aim

The aim of `RunTest.R` is to perform integration testing on the automated analysis. This integration testing is performed as part of the Jenkins build pipeline.



